// Curcible product catalog — single source of truth for the marketing site.
// Derived from Curcible_Products_Reference.md (2026-06-05).

export const HERO_IMAGE = 'https://lh3.googleusercontent.com/aida-public/AB6AXuB2OJ_h5-2UYLxKi5mxul1Y36Cfs3cq44eCd9OJNeJ5Xr8kz2fK_8BwkOdirZDsCyN7t7Mz8JBHbZaWI5fpOzNIB2UTJv8oQVLHwiD5522eDcdNrYKPNd0DQM4CBnKtwYjHIwjX56aTOno4KezgkUddS0D7pgUlVLH2E1O6HHzLtQ3ZZF0Hj2Mp21YJH-9vZtUCCPUTiP8-Ffbae8yBJKazp8AokGT2KV7JnHLTGUV5iM3v5wTysrB1eJ6IJ-wI8mKGjvlV_B9bwq0'

export const CATALOG = [
  {
    id: 'P01',
    slug: 'inboxcore',
    name: 'InboxCore™',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVs1e_ToyCwHWZ1cSWg3dptrfapYcFDgw63iqKWH-HT75RPJjjt_rBynf1WaIPsoj9kRFFmT2-i3rMseR0f9801W2oZ5vsS0m24ve9Z73K5R7A_92Dq-O_YkfWJid0NoC6pV0svnbfdHO6zZTZpLaqRRntP__fGffyLI9g3u8z2EimBQzN6G84g1X-x5dDrU3UAA0c4q22z3GlCLRlfw-Sm-BTFpHJJwZfwrfa0KdfdJkqKUWcJLq9xn6bfgHiwaSCHqoXLpCmVqI',
    category: 'Email Automation',
    tagline: 'AI Email Triage & Auto-Reply',
    price: 79,
    nodes: 11,
    setup: '1–2h',
    complexity: 'Beginner',
    gumroad: 'https://curcible.gumroad.com/l/inboxcore',
    pitch: 'Classifies every inbound Gmail into 6 categories, writes the reply, applies the label, and syncs to your CRM — without touching your inbox.',
    description: 'InboxCore connects to Gmail and processes every new unread email through a GPT-4o classification pipeline. Each message is categorised as urgent, sales, support, newsletter, spam, or general. The workflow generates a context-aware auto-reply, applies the correct Gmail label, syncs sales emails to HubSpot, creates Notion support tickets, and fires a Slack alert for anything urgent. Spam and newsletters are labelled and archived silently.',
    features: [
      '6-category AI triage classifier (customisable prompt)',
      'Context-aware auto-reply generation tuned to business context',
      'HubSpot contact sync for sales emails',
      'Notion support ticket creation',
      'Slack urgent alert routing',
      'Silent archive for spam and newsletters',
      'Full email log in Airtable',
    ],
    credentials: ['Gmail OAuth 2.0', 'OpenAI API Key (GPT-4o)', 'HubSpot Private App Token', 'Notion Integration Token', 'Slack Bot Token', 'Airtable PAT'],
    runningCost: '~$0.02–0.05 per email processed',
    bestFor: [
      'Founders handling 50+ emails/day',
      'Sales teams needing inbound leads auto-pushed to CRM',
      'Support teams wanting tickets created without manual triage',
      'Operators who want a permanent record of all inbound communication',
    ],
  },
  {
    id: 'P02',
    slug: 'contentcore',
    name: 'ContentCore™',
    category: 'Content Creation',
    tagline: 'Auto SEO Blog Writer',
    price: 79,
    nodes: 11,
    setup: '2–3h',
    complexity: 'Beginner',
    gumroad: 'https://curcible.gumroad.com/l/contentcore',
    pitch: 'Keyword in. Published draft out. Researches the SERP, writes a 1,500-word SEO article, generates a featured image, and publishes to WordPress — in under 3 minutes.',
    description: 'Send a keyword to the ContentCore webhook and the full pipeline runs automatically. SerpAPI fetches top-ranking results for competitive context. GPT-4o writes a 1,500-word SEO-optimised article with H2/H3 structure, meta description, and internal link placeholders — tuned to brand voice. DALL-E 3 generates a matching featured image. The post is pushed to WordPress as a draft, logged to a Notion content calendar, and announced in Slack.',
    features: [
      'SerpAPI SERP research integration',
      'GPT-4o article generation with customisable brand voice prompt',
      'DALL-E 3 featured image generation',
      'WordPress REST API auto-publish as draft',
      'Notion content calendar logging',
      'Configurable word count (500–4,000, default 1,500)',
      'Compatible with any REST CMS (Webflow, Ghost, Contentful)',
    ],
    credentials: ['OpenAI API Key (GPT-4o + DALL-E 3)', 'SerpAPI Key', 'WordPress Application Password', 'Notion Integration Token', 'Slack Bot Token', 'Airtable PAT'],
    runningCost: '~$0.10–0.20/article + $0.04/image',
    bestFor: [
      'Content marketers publishing 2+ posts/week',
      'SEO agencies running client content programs',
      'SaaS companies building inbound traffic with limited writing resources',
      'Founders who want organic traffic without a content team',
    ],
  },
  {
    id: 'P03',
    slug: 'leadcore',
    name: 'LeadCore™',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFn7xpnvVT1c9zvIBHY0ZOI8WkjB4WqR51nKhIoyS-n5gCjmyJK9c-Y5IMDSsv2ykQ-pPY4wfA6-SOgA3KeAOuO0Vt35NFHGMetxqN7spAXBIHfo8Zx43aVE5plZ9apNmEZ_zLB94y0OIWNjK9v6fn9b6-alfTp1MSkxy4IRQh9UDqwpQPKKDqBUcbGLXCgaW9SkR7q6xoYvEbxE8DseD_A8T9doA3w_z03KmQyey7v9jh4jTO92uVBrRL1edWEzOf_yERuOEAm3M',
    category: 'Sales Automation',
    tagline: 'AI Lead Qualification & CRM Push',
    price: 79,
    nodes: 12,
    setup: '2–4h',
    complexity: 'Intermediate',
    gumroad: 'https://curcible.gumroad.com/l/leadcore-ai-lead-qualification',
    pitch: 'Every lead enriched, scored, and routed in seconds. Apollo.io enrichment, BANT + ICP scoring via GPT-4o, HubSpot routing, and a personalised outreach email — automatically.',
    description: 'LeadCore receives inbound leads from any source via webhook. Apollo.io enriches each contact with company size, industry, seniority, and tech stack. GPT-4o runs a BANT + ICP qualification, assigning a 0–100 score and a grade of hot, warm, cold, or disqualified. Hot leads trigger a Slack alert and a HubSpot deal. All qualified leads get a HubSpot contact upsert and a personalised outreach email written from the lead’s actual context.',
    features: [
      'Apollo.io enrichment: company size, industry, seniority, tech stack',
      'BANT + ICP AI scoring (0–100, customisable ICP criteria)',
      '4-tier routing: hot / warm / cold / disqualified',
      'HubSpot deal creation for hot leads',
      'GPT-4o personalised outreach email per lead',
      'Slack hot-lead alerts',
      'Compatible with Salesforce, Pipedrive, or any HTTP CRM',
    ],
    credentials: ['OpenAI API Key (GPT-4o)', 'Apollo.io API Key', 'HubSpot Private App Token', 'Gmail OAuth 2.0', 'Airtable PAT'],
    runningCost: '~$0.05/lead + Apollo.io free tier',
    bestFor: [
      'B2B SaaS teams receiving inbound demo requests',
      'Sales teams needing leads enriched and scored before outreach',
      'Agencies running lead generation programs',
      'Revenue ops teams building a structured qualification process',
    ],
  },
  {
    id: 'P04',
    slug: 'postcore',
    name: 'PostCore™',
    category: 'Social Media',
    tagline: 'Social Media Auto-Publisher',
    price: 79,
    nodes: 12,
    setup: '3–5h',
    complexity: 'Intermediate',
    gumroad: 'https://curcible.gumroad.com/l/postcore',
    pitch: 'One topic. Four platforms. One workflow. Platform-native posts for Twitter/X, LinkedIn, Instagram, and Facebook with a DALL-E 3 image — published simultaneously.',
    description: 'Send a topic to the PostCore webhook (or let the schedule trigger fire) and GPT-4o generates platform-native posts optimised for each network’s format and character constraints. DALL-E 3 generates a matching image. Posts publish simultaneously to all four platforms, Slack confirms the run, and Airtable logs theme, posts, image URL, and timestamp.',
    features: [
      'GPT-4o platform-native post generation (4 platforms)',
      'DALL-E 3 image generation per run',
      'Dual trigger: webhook + cron schedule (default Mon/Wed/Fri 9am)',
      'Configurable schedule (any cron expression)',
      'Individual platform nodes — disable any without affecting others',
      'Slack publish confirmation',
      'Full Airtable run log',
    ],
    credentials: ['OpenAI API Key (GPT-4o + DALL-E 3)', 'Twitter/X API v2 Bearer Token', 'LinkedIn OAuth 2.0', 'Meta Graph API Token', 'Slack Bot Token', 'Airtable PAT'],
    runningCost: '~$0.05–0.10/run + $0.04/image',
    bestFor: [
      'Marketing teams needing daily social presence without a content team',
      'Agencies managing multiple client social accounts',
      'Founders who want consistent posting without dedicating hours',
      'Growth teams running content-led acquisition',
    ],
  },
  {
    id: 'P05',
    slug: 'reportcore',
    name: 'ReportCore™',
    category: 'Analytics & Reporting',
    tagline: 'Weekly Analytics Digest',
    price: 79,
    nodes: 14,
    setup: '2–4h',
    complexity: 'Intermediate',
    gumroad: 'https://curcible.gumroad.com/l/reportcore',
    pitch: 'Your Monday morning briefing, automated. Pulls GA4, Stripe, and HubSpot data, generates an executive narrative with GPT-4o, and delivers to Notion, Slack, and Gmail.',
    description: 'ReportCore runs on a Monday morning schedule or on demand. It fetches GA4 sessions and users, Stripe revenue, and HubSpot pipeline values in parallel, aggregates the metrics, and GPT-4o writes an executive narrative with highlights, concerns, insights, and recommendations. The report publishes to Notion, posts to Slack, and ships as an HTML email digest.',
    features: [
      'Parallel data fetch from GA4, Stripe, and HubSpot',
      'GPT-4o executive narrative: highlights, concerns, insights, recommendations',
      'Notion report page creation',
      'Slack block-format digest',
      'Gmail HTML email delivery to distribution list',
      'Extensible: add any additional data source',
      'Configurable schedule (any cron expression)',
    ],
    credentials: ['OpenAI API Key (GPT-4o)', 'GA4 OAuth Token', 'Stripe Secret Key', 'HubSpot Private App Token', 'Notion Integration Token', 'Slack Bot Token', 'Gmail OAuth 2.0', 'Airtable PAT'],
    runningCost: '~$0.10–0.15/report — data source queries are free',
    bestFor: [
      'Founders who want a weekly business pulse without dashboards',
      'Marketing leads tracking content and pipeline performance',
      'Operations teams reporting to leadership weekly',
      'Agencies preparing weekly client reports',
    ],
  },
  {
    id: 'P06',
    slug: 'knowcore',
    name: 'KnowCore™',
    category: 'Customer Service',
    tagline: 'WhatsApp AI Chatbot + RAG',
    price: 99,
    nodes: 12,
    setup: '4–6h',
    complexity: 'Advanced',
    gumroad: 'https://curcible.gumroad.com/l/knowcore',
    pitch: 'A WhatsApp assistant that knows your business. Pinecone RAG, intent classification, human escalation, and full conversation logging.',
    description: 'KnowCore receives WhatsApp messages via a Twilio webhook. GPT-4o-mini classifies intent (question, complaint, booking, sales, escalate), Pinecone retrieves the 5 most relevant knowledge-base chunks, and GPT-4o generates a grounded response from that context only. Low confidence or explicit requests escalate to a human via Slack. Every conversation pair is logged with intent and confidence.',
    features: [
      'Twilio WhatsApp Business integration',
      'GPT-4o-mini fast intent classification (5 intents)',
      'Pinecone vector search RAG (top 5 chunks)',
      'Grounded responses — answers only from your knowledge base',
      'Automatic human escalation to Slack',
      'Multilingual — detects language and responds in kind',
      'Python ingestion script included for KB setup',
      'Compatible with Supabase pgvector, Weaviate, or Qdrant',
    ],
    credentials: ['OpenAI API Key (GPT-4o + GPT-4o-mini)', 'Twilio SID + Auth Token', 'Pinecone API Key', 'Slack Bot Token', 'Airtable PAT'],
    runningCost: '~$0.01–0.03/message + ~$0.005/message (Twilio)',
    bestFor: [
      'E-commerce stores with high repeat question volume',
      'Hospitality businesses fielding availability and booking queries',
      'Clinics and service businesses answering appointment questions',
      'Any SMB with 50+ repetitive WhatsApp inquiries per day',
    ],
  },
  {
    id: 'P07',
    slug: 'meetcore',
    name: 'MeetCore™',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCI0FUfnrtRGmJB17oBwi4tgW5XX0x-YEHu-SGMJnwwkURDUC96gCtHMm7zpiCA2g1zRzh-TX9o-ww_vjkHEtyQvaL9TqVZG6rnihoXBBzM3XGrbvqpu9HTObYuME-8dDxWs4x8ZiujKxQWBFwCKPHwAoNe4_eZ_2Ybj2bN0XhSlgyckpWKiH8DEPUXc459AznC-KXoYRrH5e5uzciqPfNghT8Y5oVXr2v-yA5NAwaUQH61oH6BSLCo0YGbkI0AtO97W2QnNccAu_s',
    category: 'Productivity',
    tagline: 'AI Meeting Summary & Follow-Up',
    price: 79,
    nodes: 16,
    setup: '2–4h',
    complexity: 'Intermediate',
    gumroad: 'https://curcible.gumroad.com/l/meetcore',
    pitch: 'Audio in. Action items out. Transcribes, analyses, and distributes your meetings — summary, action items, follow-up email, CRM note, calendar event, and Slack digest in one run.',
    description: 'MeetCore accepts an audio URL (transcribed by AssemblyAI with speaker labels) or a pasted transcript. GPT-4o extracts an executive summary, action items with owner/due date/priority, decisions, open questions, sentiment, and a complete follow-up email draft. Six outputs fire in parallel: Notion page, Slack digest, Gmail follow-up, HubSpot engagement note, Google Calendar follow-up event, and an Airtable log.',
    features: [
      'AssemblyAI audio transcription with speaker labels',
      'GPT-4o extraction: summary, action items, decisions, questions, sentiment',
      'Follow-up email drafted and sent to all attendees',
      '6 parallel outputs: Notion, Slack, Gmail, HubSpot, Calendar, Airtable',
      'Sales meeting mode: auto HubSpot engagement creation',
      'Dual input: audio URL or direct transcript paste',
      'Zoom webhook compatible (meeting.ended event)',
    ],
    credentials: ['OpenAI API Key (GPT-4o)', 'AssemblyAI API Key', 'Notion Integration Token', 'Slack Bot Token', 'Gmail OAuth 2.0', 'HubSpot Private App Token', 'Google Calendar OAuth 2.0', 'Airtable PAT'],
    runningCost: '~$0.00025/sec audio + ~$0.05–0.15/meeting',
    bestFor: [
      'Teams running 5+ meetings/week needing automatic documentation',
      'Sales teams who need call notes logged to HubSpot automatically',
      'Ops leads who want meeting accountability and follow-up built in',
      'Consultants who bill by the meeting and need clean records',
    ],
  },
  {
    id: 'P08',
    slug: 'schedcore',
    name: 'SchedCore™',
    category: 'Scheduling',
    tagline: 'AI Scheduling & Booking Automation',
    price: 79,
    nodes: 13,
    setup: '2–3h',
    complexity: 'Intermediate',
    gumroad: 'https://curcible.gumroad.com/l/schedcore',
    pitch: 'Booking handled. No back-and-forth. Checks your calendar, picks the best slot with GPT-4o, creates the event, and sends email and SMS confirmations.',
    description: 'SchedCore receives booking requests from web forms, Calendly webhooks, or WhatsApp. It queries Google Calendar free/busy for the next 7 business days, generates up to 6 available slots, and GPT-4o recommends the optimal time from meeting type and requester notes. The workflow creates the calendar event with an AI-generated agenda, sends a branded confirmation email, fires a Twilio SMS, logs to HubSpot, and records everything in Airtable.',
    features: [
      'Google Calendar free/busy check (7-day look-ahead)',
      'GPT-4o slot recommendation from meeting type and context',
      'Calendar event creation with AI-generated agenda',
      'Branded HTML confirmation email + Twilio SMS',
      'Dual webhook: direct booking + Calendly booking.created',
      'HubSpot engagement logging',
      'Configurable working hours (default 9am–5pm Mon–Fri)',
    ],
    credentials: ['OpenAI API Key (GPT-4o)', 'Google Calendar OAuth 2.0', 'Gmail OAuth 2.0', 'Twilio SID + Auth Token', 'HubSpot Private App Token', 'Airtable PAT'],
    runningCost: '~$0.02/booking + ~$0.0079/SMS',
    bestFor: [
      'Consultants and agencies fielding discovery call requests',
      'Clinics and service businesses managing appointment bookings',
      'Teams using Calendly who want post-booking automation',
      'Businesses receiving bookings via web forms or WhatsApp',
    ],
  },
]

export const getProduct = slug => CATALOG.find(p => p.slug === slug)
