// ─── Static SAMPLE dataset ────────────────────────────────────────────────────
// Replaces the former generative "LLM-invents-leads" path. These rows are
// fictional, clearly watermarked, and NON-EXPORTABLE. Purpose: let a first-run
// user see the pipeline and results UI before a Google Places key is configured.
//
// No external call. No fabricated PII about real people. Every row carries
// is_sample: true so the UI can badge it and the exporter can refuse it.

export const SAMPLE_LEADS = [
  {
    is_sample: true,
    name: 'Sample Plumbing Co (DEMO)',
    address: '100 Example Ave, Sampleton',
    phone: '+1 (555) 010-0000',
    phone_valid: true, phone_type: 'FIXED_LINE', phone_formatted: '+1 555 010 0000',
    email: 'demo@example.com', email_format_valid: true, email_source: 'sample',
    website: 'https://example.com', url_format_valid: true, web_verified: true,
    social_only: false,
    industry: 'Plumbing',
    score: 'hot', buy_probability: 88,
    website_quality: 'Single-page site, no booking — sample copy.',
    services: ['Emergency repair', 'Drain cleaning'],
    tech_stack: ['Wix'],
    pain_points: ['Misses after-hours calls', 'No online booking'],
    problem_solved: 'Loses jobs after hours because no one answers the phone — illustrative only.',
    sale_strategy: 'Open on missed-call revenue. Position SchedCore for 24/7 booking. Close on a 2-week pilot. (Sample text.)',
    recommended_products: ['P08', 'P01'],
    notes: 'Sample row — not a real business.',
    confidence: 4,
    places_id: 'SAMPLE-0001',
    maps_url: '',
  },
  {
    is_sample: true,
    name: 'Demo Dental Studio (DEMO)',
    address: '200 Placeholder Rd, Sampleton',
    phone: '+1 (555) 010-0001',
    phone_valid: true, phone_type: 'FIXED_LINE', phone_formatted: '+1 555 010 0001',
    email: 'demo@example.com', email_format_valid: true, email_source: 'sample',
    website: 'https://example.com', url_format_valid: true, web_verified: true,
    social_only: false,
    industry: 'Dental Practice',
    score: 'hot', buy_probability: 82,
    website_quality: 'Outdated template, no recall reminders — sample copy.',
    services: ['General dentistry', 'Whitening'],
    tech_stack: ['WordPress'],
    pain_points: ['No appointment reminders', 'High no-show rate'],
    problem_solved: 'No-shows erode the schedule because reminders are manual — illustrative only.',
    sale_strategy: 'Lead with no-show cost. Position SchedCore reminders. Close on per-chair ROI. (Sample text.)',
    recommended_products: ['P08'],
    notes: 'Sample row — not a real business.',
    confidence: 4,
    places_id: 'SAMPLE-0002',
    maps_url: '',
  },
  {
    is_sample: true,
    name: 'Example Hair Salon (DEMO)',
    address: '300 Mock St, Sampleton',
    phone: '+1 (555) 010-0002',
    phone_valid: true, phone_type: 'FIXED_LINE', phone_formatted: '+1 555 010 0002',
    email: 'demo@example.com', email_format_valid: true, email_source: 'sample',
    website: 'https://example.com', url_format_valid: true, web_verified: true,
    social_only: false,
    industry: 'Hair Salon',
    score: 'hot', buy_probability: 76,
    website_quality: 'Instagram only, no website — sample copy.',
    services: ['Cuts', 'Color'],
    tech_stack: [],
    pain_points: ['No website', 'DMs go unanswered'],
    problem_solved: 'Bookings stall in unread DMs — illustrative only.',
    sale_strategy: 'Open on lost DM bookings. Position KnowCore auto-reply. Close on a one-month trial. (Sample text.)',
    recommended_products: ['P06', 'P04'],
    notes: 'Sample row — not a real business.',
    confidence: 3,
    places_id: 'SAMPLE-0003',
    maps_url: '',
  },
  {
    is_sample: true,
    name: 'Sampletown Law Group (DEMO)',
    address: '400 Demo Blvd, Sampleton',
    phone: '+1 (555) 010-0003',
    phone_valid: true, phone_type: 'FIXED_LINE', phone_formatted: '+1 555 010 0003',
    email: 'demo@example.com', email_format_valid: true, email_source: 'sample',
    website: 'https://example.com', url_format_valid: true, web_verified: true,
    social_only: false,
    industry: 'Law Firm',
    score: 'hot', buy_probability: 71,
    website_quality: 'Slow site, no intake form — sample copy.',
    services: ['Family law', 'Estate planning'],
    tech_stack: ['WordPress'],
    pain_points: ['Slow intake response', 'Manual follow-up'],
    problem_solved: 'Prospective clients drop off before intake is returned — illustrative only.',
    sale_strategy: 'Open on intake speed-to-lead. Position InboxCore triage. Close on caseload math. (Sample text.)',
    recommended_products: ['P01', 'P07'],
    notes: 'Sample row — not a real business.',
    confidence: 3,
    places_id: 'SAMPLE-0004',
    maps_url: '',
  },
  {
    is_sample: true,
    name: 'Mock Fitness Studio (DEMO)',
    address: '500 Test Loop, Sampleton',
    phone: '+1 (555) 010-0004',
    phone_valid: true, phone_type: 'FIXED_LINE', phone_formatted: '+1 555 010 0004',
    email: 'demo@example.com', email_format_valid: true, email_source: 'sample',
    website: 'https://example.com', url_format_valid: true, web_verified: true,
    social_only: false,
    industry: 'Fitness & Gym',
    score: 'hot', buy_probability: 69,
    website_quality: 'Basic site, no lead capture — sample copy.',
    services: ['Personal training', 'Classes'],
    tech_stack: ['Squarespace'],
    pain_points: ['No lead capture', 'Inconsistent social posting'],
    problem_solved: 'Trial interest is never captured or followed up — illustrative only.',
    sale_strategy: 'Open on trial-to-member conversion. Position LeadCore + PostCore. Close on a 30-day pilot. (Sample text.)',
    recommended_products: ['P03', 'P04'],
    notes: 'Sample row — not a real business.',
    confidence: 3,
    places_id: 'SAMPLE-0005',
    maps_url: '',
  },
  {
    is_sample: true,
    name: 'Placeholder Auto Repair (DEMO)',
    address: '600 Sample Way, Sampleton',
    phone: '+1 (555) 010-0005',
    phone_valid: true, phone_type: 'FIXED_LINE', phone_formatted: '+1 555 010 0005',
    email: 'demo@example.com', email_format_valid: true, email_source: 'sample',
    website: 'https://example.com', url_format_valid: true, web_verified: true,
    social_only: false,
    industry: 'Auto Repair',
    score: 'hot', buy_probability: 67,
    website_quality: 'No site, Google listing only — sample copy.',
    services: ['Brakes', 'Diagnostics'],
    tech_stack: [],
    pain_points: ['No website', 'Phone tag for quotes'],
    problem_solved: 'Quote requests stall in phone tag — illustrative only.',
    sale_strategy: 'Open on quote turnaround. Position SchedCore + InboxCore. Close on bays-filled math. (Sample text.)',
    recommended_products: ['P08', 'P01'],
    notes: 'Sample row — not a real business.',
    confidence: 2,
    places_id: 'SAMPLE-0006',
    maps_url: '',
  },
]

export const SAMPLE_RUN_META = {
  locationState: 'Sampleton',
  locationCountry: 'United States',
  blueprintProduct: 'P08',
  productName: 'Sample run',
  dataSource: 'sample',
  isSample: true,
}
